"""empty message

Revision ID: 8c495c494357
Revises: 8a75fd665b7f
Create Date: 2019-06-28 12:42:54.493234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c495c494357'
down_revision = '8a75fd665b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user', 'is_active')
    # ### end Alembic commands ###
